// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219055126_InicializarBaseDeDatos")]
    partial class InicializarBaseDeDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebApi.Data.TA_POKEMON", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FECHA_CAPTURA")
                        .HasColumnType("TEXT");

                    b.Property<int>("NIVEL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TA_POKEMON");
                });
#pragma warning restore 612, 618
        }
    }
}
